// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCicfWhIj5_fti-KC0RoWh6xX5BhJ__YB0',
    appId: '1:640977639084:web:d6bc0040f75d6b82577109',
    messagingSenderId: '640977639084',
    projectId: 'days-of-flutter-2e7af',
    authDomain: 'days-of-flutter-2e7af.firebaseapp.com',
    storageBucket: 'days-of-flutter-2e7af.appspot.com',
    measurementId: 'G-KVEDZ7KJJD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAy6YmZ1zaFDXeIkfFGf7Z8Y05e0Znyy08',
    appId: '1:640977639084:android:07a807e5cce9f82d577109',
    messagingSenderId: '640977639084',
    projectId: 'days-of-flutter-2e7af',
    storageBucket: 'days-of-flutter-2e7af.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZuL3onUAM5JkWCFgXEmJUGqFwwOpqCjk',
    appId: '1:640977639084:ios:9634d896e6e7e7ab577109',
    messagingSenderId: '640977639084',
    projectId: 'days-of-flutter-2e7af',
    storageBucket: 'days-of-flutter-2e7af.appspot.com',
    iosBundleId: 'com.example.flutterChallenge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZuL3onUAM5JkWCFgXEmJUGqFwwOpqCjk',
    appId: '1:640977639084:ios:9634d896e6e7e7ab577109',
    messagingSenderId: '640977639084',
    projectId: 'days-of-flutter-2e7af',
    storageBucket: 'days-of-flutter-2e7af.appspot.com',
    iosBundleId: 'com.example.flutterChallenge',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCicfWhIj5_fti-KC0RoWh6xX5BhJ__YB0',
    appId: '1:640977639084:web:47a03dcc4f28619b577109',
    messagingSenderId: '640977639084',
    projectId: 'days-of-flutter-2e7af',
    authDomain: 'days-of-flutter-2e7af.firebaseapp.com',
    storageBucket: 'days-of-flutter-2e7af.appspot.com',
    measurementId: 'G-72KQYNRZGV',
  );
}
